"""Turns the approved chapters into book.md and evidence.md. Pure code, no model calls."""
import re

from core.state import BookState, Fact, Page
from core.text import CITE_RE, split_sentences

VERDICT_LABELS = {
    "supports": "✅ supports",
    "partly": "⚠️ partly supports",
    "does_not_support": "❌ does not support",
    "uncited_claim": "❌ uncited claim",
}


def number_citations(body: str, facts: dict[str, Fact], pages: dict[str, Page]) -> tuple[str, list[Page]]:
    """Replace [F#] with [1], [2]… numbered by source page in order of first use.

    Facts from the same page share one reference number.
    """
    order: list[str] = []
    for fact_id in CITE_RE.findall(body):
        fact = facts.get(fact_id)
        if fact and fact.page_id not in order:
            order.append(fact.page_id)
    numbers = {page_id: n for n, page_id in enumerate(order, 1)}
    return apply_numbers(body, facts, numbers), [pages[page_id] for page_id in order]


def apply_numbers(text: str, facts: dict[str, Fact], numbers: dict[str, int]) -> str:
    def renumber(match: re.Match) -> str:
        fact = facts.get(match.group(1))
        return f"[{numbers[fact.page_id]}]" if fact else ""

    text = CITE_RE.sub(renumber, text)
    text = re.sub(r"\[(\d+)\](?:\s*\[\1\])+", r"[\1]", text)   # [2][2] -> [2]
    return re.sub(r"\s+([.,;:!?])", r"\1", text)                # tidy space left by a dropped ID


def reference_line(number: int, page: Page) -> str:
    return f'[{number}] {page.source}. "{page.title}." {page.url}'


def render_book(state: BookState) -> str:
    facts = {f.id: f for f in state.facts}
    pages = {p.id: p for p in state.pages}
    lines = [f"# {state.brief.title}", "", f"*A friendly guide for {state.brief.audience[0].lower() + state.brief.audience[1:]}*", ""]
    for chapter in state.chapters:
        body, references = number_citations(chapter.body, facts, pages)
        lines += [f"## Chapter {chapter.number}: {chapter.title}", "", body, "", chapter.takeaway.strip(), "",
                  "### References", ""]
        for number, page in enumerate(references, 1):
            lines += [reference_line(number, page), ""]
    return "\n".join(lines)


def render_evidence(state: BookState) -> str:
    facts = {f.id: f for f in state.facts}
    pages = {p.id: p for p in state.pages}
    verdicts = {(c.chapter, c.sentence): c for c in state.fact_checks}
    lines = [
        "# Evidence for every citation",
        "",
        "Generated by code. For each cited sentence in the book: the source, the exact words on that page "
        "that support it, and the Fact-checker's verdict.",
        "",
    ]
    for chapter in state.chapters:
        _, references = number_citations(chapter.body, facts, pages)
        numbers = {page.id: n for n, page in enumerate(references, 1)}
        lines += [f"## Chapter {chapter.number}: {chapter.title}", ""]
        for sentence in split_sentences(chapter.body):
            fact_ids = [fid for fid in dict.fromkeys(CITE_RE.findall(sentence)) if fid in facts]
            if not fact_ids:
                continue
            lines += [f"**Sentence:** {apply_numbers(sentence, facts, numbers)}", ""]
            for fid in fact_ids:
                fact = facts[fid]
                page = pages[fact.page_id]
                lines += [f"- {reference_line(numbers[page.id], page)}", f'  > "{fact.quote}"']
            check = verdicts.get((chapter.number, sentence))
            label = VERDICT_LABELS[check.verdict] if check else "not reviewed"
            if check and check.note.strip().lower() not in ("", "ok"):
                label += f" ({check.note})"
            lines += [f"- Fact-checker: {label}", ""]
    return "\n".join(lines)


def render_run_log(state: BookState) -> str:
    lines = ["# Run log", "", "Every hand-off between agents, in order.", "", "```", *state.log, "```", ""]
    lines += ["## Summary", "", f"- Gemini calls used: {state.llm_calls}",
              f"- Revision rounds: {state.revision_round}",
              f"- Sources fetched: {len(state.pages)}; verified facts: {len(state.facts)}", ""]
    if state.warnings:
        lines += ["## Warnings", "", *[f"- {w}" for w in state.warnings], ""]
    return "\n".join(lines)
